services:

  db:
    image: 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    container_name: forms-service
    build:
      dockerfile: ./Dockerfile
      context: ./

    volumes:
      - ./logs/api:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: .env




volumes:
  postgres_data:
